document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__0__QuestionData_PostalCodeAnswer').value += '29222';
document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__2__QuestionData_UserAnswer').selectedIndex = 12;
document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__7__QuestionData_DateAnswer').value += '01';
document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__7__QuestionData_DateAnswer').value += '01';
document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__7__QuestionData_DateAnswer').value += '1965';
document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__8__QuestionData_UserAnswer').checked = true;
document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__13__QuestionData_DateAnswer').value += '01';
document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__13__QuestionData_DateAnswer').value += '01';
document.getElementById('Page_GetQuote__ProductQuestionCodes_QUOTE__13__QuestionData_DateAnswer').value += '1970';
var z = document.getElementsByName('Page[GetQuote].ProductQuestionCodes[QUOTE][14].QuestionData.UserAnswer');
console.log(z);
